// Angular/HW/3/Cards/src/app/products/products.component.ts
import {Component, OnInit} from '@angular/core';

class Product {
  constructor
  (
    public img: string,
    public name: string,
    public list_text: string[]
  ) {}
}

@Component
({
  selector: 'app-product',
  standalone: true,
  imports: [],
  templateUrl: './products.component.html',
  styleUrl: './products.component.css'
})
export class ProductComponent implements OnInit 
{
  products: Product[];

  constructor() { this.products = []; }

  ngOnInit(): void 
  {
    const productData = [
      {
        img: '',
        name: 'Ноутбуки',
        list_text: []
      },

      {
        img: '',
        name: 'Компьютеры',
        list_text: []
      },

      {
        img: '',
        name: 'Мониторы',
        list_text: []
      },

      {
        img: '',
        name: 'Gaming',
        list_text: []
      },

      {
        img: '',
        name: 'Планшеты',
        list_text: []
      },

      {
        img: '',
        name: 'Кабели и переходники',
        list_text: []
      },

      {
        img: '',
        name: 'Кмп. комплектующие',
        list_text: ['SSD', 'Системы охлаждения', 'Видеокарты', 'Оперативная память', 'Процессоры', 'Материнские платы', 'Жесткие диски и дисковые массивы', 'Блоки питания']
      },

      {
        img: '',
        name: 'Сетевое оборудование',
        list_text: ['Маршрутизаторы', 'Коммутаторы', 'Сетевые адаптеры', 'Пассивное сетевое оборудование', 'Беспроводные точки доступа', 'Ретрансляторы Wi-Fi', 'Патч-корды']
      },

      {
        img: '',
        name: 'Наушники и аксессуары',
        list_text: ['Наушники', 'TWS', 'Игровые гарнитуры', 'Вакуумные наушники', 'Наушники вкладыши', 'Накладные наушники', 'Полноразмерные наушники', 'Усилители для наушников', 'Аксессуары для наушников']
      },

      {
        img: '',
        name: 'Клавиатуры и мыши',
        list_text: ['Компьютерные мыши', 'Игровые поверхности', 'Клавиатуры', 'Комплект: клавиатура и мышь', 'Аксессуары для клавиатур и мышей', 'Мышек']
      },

      {
        img: '',
        name: 'Аксессуары',
        list_text: ['Флеш память USB', 'Хабы и кардридеры', 'Аксессуары для ПК и ноутбуков', 'Комплектующие для ноутбуков', 'Сетевые фильтры, адаптеры и удлинители', 'Чехлы для планшетов', 'Сумки, рюкзаки и чехлы для ноутбуков', 'Чистящие средства']
      },

      {
        img: '',
        name: 'Оргтехника',
        list_text: ['МФУ/Принтеры', 'Сканеры', 'Расходные материалы для принтера', 'Доски, флипчарты']
      }
    ];

    for (const data of productData) 
    {
      this.products.push(new Product(data.img, data.name, data.list_text));
    }

  }
}
<div class="products-container">
    <div class="product">
      <img [src]="products[0].img" alt="{{ products[0].name }}">
      <h3>{{ products[0].name }}</h3>
    </div>


    <div class="product">
      <img [src]="products[1].img" alt="{{ products[1].name }}">
      <h3>{{ products[1].name }}</h3>
    </div>


    <div class="product">
      <img [src]="products[2].img" alt="{{ products[2].name }}">
      <h3>{{ products[2].name }}</h3>
    </div>


    <div class="product">
      <img [src]="products[3].img" alt="{{ products[3].name }}">
      <h3>{{ products[3].name }}</h3>
    </div>


    <div class="product">
      <img [src]="products[4].img" alt="{{ products[4].name }}">
      <h3>{{ products[4].name }}</h3>
    </div>

    
    <div class="product">
      <img [src]="products[5].img" alt="{{ products[5].name }}">
      <h3>{{ products[5].name }}</h3>
    </div>


    <div class="product">
      <img [src]="products[6].img" alt="{{ products[6].name }}">
      <h3>{{ products[6].name }}</h3>
      <ul>
        <li>{{ products[6].list_text[0] }}</li>
        <li>{{ products[6].list_text[1] }}</li>
        <li>{{ products[6].list_text[2] }}</li>
        <li>{{ products[6].list_text[3] }}</li>
        <li>{{ products[6].list_text[4] }}</li>
        <li>{{ products[6].list_text[5] }}</li>
        <li>{{ products[6].list_text[6] }}</li>
        <li>{{ products[6].list_text[7] }}</li>
      </ul>
    </div>

    
    <div class="product">
      <img [src]="products[7].img" alt="{{ products[7].name }}">
      <h3>{{ products[7].name }}</h3>
      <ul>
        <li>{{ products[7].list_text[0] }}</li>
        <li>{{ products[7].list_text[1] }}</li>
        <li>{{ products[7].list_text[2] }}</li>
        <li>{{ products[7].list_text[3] }}</li>
        <li>{{ products[7].list_text[4] }}</li>
        <li>{{ products[7].list_text[5] }}</li>
      </ul>
    </div>


    <div class="product">
      <img [src]="products[8].img" alt="{{ products[8].name }}">
      <h3>{{ products[8].name }}</h3>
      <ul>
        <li>{{ products[8].list_text[0] }}</li>
        <li>{{ products[8].list_text[1] }}</li>
        <li>{{ products[8].list_text[2] }}</li>
        <li>{{ products[8].list_text[3] }}</li>
        <li>{{ products[8].list_text[4] }}</li>
        <li>{{ products[8].list_text[5] }}</li>
        <li>{{ products[8].list_text[6] }}</li>
        <li>{{ products[8].list_text[7] }}</li>
      </ul>
    </div>


    <div class="product">
      <img [src]="products[9].img" alt="{{ products[9].name }}">
      <h3>{{ products[9].name }}</h3>
      <ul>
        <li>{{ products[9].list_text[0] }}</li>
        <li>{{ products[9].list_text[1] }}</li>
        <li>{{ products[9].list_text[2] }}</li>
        <li>{{ products[9].list_text[3] }}</li>
        <li>{{ products[9].list_text[4] }}</li>
      </ul>
    </div>


    <div class="product">
      <img [src]="products[10].img" alt="{{ products[10].name }}">
      <h3>{{ products[10].name }}</h3>
      <ul>
        <li>{{ products[10].list_text[0] }}</li>
        <li>{{ products[10].list_text[1] }}</li>
        <li>{{ products[10].list_text[2] }}</li>
        <li>{{ products[10].list_text[3] }}</li>
        <li>{{ products[10].list_text[4] }}</li>
        <li>{{ products[10].list_text[5] }}</li>
        <li>{{ products[10].list_text[6] }}</li>
        <li>{{ products[10].list_text[7] }}</li>
      </ul>
    </div>


    <div class="product">
      <img [src]="products[11].img" alt="{{ products[11].name }}">
      <h3>{{ products[11].name }}</h3>
      <ul>
        <li>{{ products[11].list_text[0] }}</li>
        <li>{{ products[11].list_text[1] }}</li>
        <li>{{ products[11].list_text[2] }}</li>
        <li>{{ products[11].list_text[3] }}</li>
      </ul>
    </div>
    
  </div>

// React/HW/5/cards-roz/src/components/products.js
import React from 'react';
import './products.css';

function SectionElement({ src, alt, linkText, href, additionalLinks }) {
    return (
        <div className='section__element'>
            <img src={src} alt={alt}></img>
            <a href={href}>
                <span className='section__text-header'>{linkText}</span>
            </a>
            {additionalLinks && (
                <div className='section__element-links'>
                    {additionalLinks.map((link, index) => (
                        <a key={index} href={link.href}><span>{link.text}</span></a>
                    ))}
                </div>
            )}
        </div>
    );
}

export class Section extends React.Component {
    render() {
        return (
            <div className='section'>
                <div className='section__elements'>
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/noutbuki.png"
                        alt="Ноутбуки"
                        linkText="Ноутбуки"
                        href="#"
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/kompyutery.png"
                        alt="Компьютеры, неттопы, моноблоки"
                        linkText="Компьютеры, неттопы, моноблоки"
                        href="#"
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/monitory.png"
                        alt="Мониторы"
                        linkText="Мониторы"
                        href="#"
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/tovary-dlya-gejmerov.png"
                        alt="Gaming"
                        linkText="Gaming"
                        href="#"
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/planshety.png"
                        alt="Планшеты"
                        linkText="Планшеты"
                        href="#"
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/kabeli-i-perekhodniki.png"
                        alt="Кабели и переходники"
                        linkText="Кабели и переходники"
                        href="#"
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/kompyuternye-komplektuyushchie.png"
                        alt="Компьютерные комплектующие"
                        linkText="Компьютерные комплектующие"
                        href="#"
                        additionalLinks={[
                            { href: '#', text: 'SSD' },
                            { href: '#', text: 'Системы охлаждения' },
                            { href: '#', text: 'Видеокарты' },
                            { href: '#', text: 'Оперативная память' },
                            { href: '#', text: 'Процессоры' },
                            { href: '#', text: 'Материнские платы' },
                            { href: '#', text: 'Жесткие диски' },
                            { href: '#', text: 'Блоки питания' }
                        ]}
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/setevoe-oborudovanie.png"
                        alt="Сетевое оборудование"
                        linkText="Сетевое оборудование"
                        href="#"
                        additionalLinks={[
                            { href: '#', text: 'Маршрутизаторы' },
                            { href: '#', text: 'Коммутаторы' },
                            { href: '#', text: 'Сетевые адаптеры' },
                            { href: '#', text: 'Пассивное сетевое оборудование' },
                            { href: '#', text: 'Точки доступа Wi-Fi' },
                            { href: '#', text: 'Ретрансляторы Wi-Fi сигнала' },
                            { href: '#', text: 'Патч-корды' }
                        ]}
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/naushniki-i-aksessuary.png"
                        alt="Наушники и аксессуары"
                        linkText="Наушники и аксессуары"
                        href="#"
                        additionalLinks={[
                            { href: '#', text: 'Наушники' },
                            { href: '#', text: 'TWS' },
                            { href: '#', text: 'Игровые гарнитуры' },
                            { href: '#', text: 'Вакуумные наушники' },
                            { href: '#', text: 'Наушники вкладыши' },
                            { href: '#', text: 'Накладные наушники' },
                            { href: '#', text: 'Полноразмерные наушники' },
                            { href: '#', text: 'Усилители для наушников' },
                            { href: '#', text: 'Аксессуары для наушников' }
                        ]}
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/klaviatury-i-myshi.png"
                        alt="Клавиатуры и мыши"
                        linkText="Клавиатуры и мыши"
                        href="#"
                        additionalLinks={[
                            { href: '#', text: 'Компьютерные мыши' },
                            { href: '#', text: 'Коврики для мыши' },
                            { href: '#', text: 'Клавиатуры' },
                            { href: '#', text: 'Комплекты клавиатуры и мыши' },
                            { href: '#', text: 'Аксессуары для клавиатур и мышей' }
                        ]}
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/aksessuari-dlia-elektronyky.png"
                        alt="Аксессуары для электроники"
                        linkText="Аксессуары для электроники"
                        href="#"
                        additionalLinks={[
                            { href: '#', text: 'USB флешки' },
                            { href: '#', text: 'Хабы и кардридеры' },
                            { href: '#', text: 'Аксессуары для ПК и ноутбуков' },
                            { href: '#', text: 'Комплектующие для ноутбуков' },
                            { href: '#', text: 'Сетевые фильтры' },
                            { href: '#', text: 'Чехлы и клавиатуры для планшетов' },
                            { href: '#', text: 'Сумки, рюкзаки и чехлы для ноутбуков' },
                            { href: '#', text: 'Чистящие средства' }
                        ]}
                    />
                    <SectionElement
                        src="https://video.rozetka.com.ua/img_superportal/kompyutery_i_noutbuki/ofisnaya-tekhnika.png"
                        alt="Офисная техника"
                        linkText="Офисная техника"
                        href="#"
                        additionalLinks={[
                            { href: '#', text: 'Принтеры и МФУ' },
                            { href: '#', text: 'Сканеры' },
                            { href: '#', text: 'Расходные материалы для принтеров' },
                            { href: '#', text: 'Доски, флипчарты' }
                        ]}
                    />
                </div>
            </div>
        );
    }
}
